language: node_js
dist: trusty

node_js:
  - "node"

before_script:
  - echo $JAVA_HOME
  - java -version
  - gradle -version
  - npm run build

deploy:
  provider: npm
  skip_cleanup: true
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
